config/routes.rb
Rbghub::Application.routes.draw do

  resources :teamstats

  resources :characters

  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'roster' => 'characters#index'
  get 'stats' => 'teamstats#new'
  

  get 'sitemap.xml' => "pages#sitemap.xml"

 root 'teamstats#new'

  

end

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<div class="hero-unit">
	<center>
		<p><h1 class="brand"><%= yield(:title)%></h1></p>
		<hr>
	</center>


	<p>
	<h2>How It Works</h2>
		<ol>
			<li>Start by <%= link_to "creating an account", new_user_registration_path %>. You can also include your Skype and <%= link_to "BattleTag", "http://us.battle.net/en/battletag/", :target => "_blank" %> IDs along with some basic bio information to make it easier to find a group, or skip it to save time (you can always update your account info later!)</li>
			<li>Next, add some toons to your <%= link_to "roster", characters_path %>. This is a one-time setup for each toon you with to RBG with and takes about 30 seconds per character.</li>
			<li>Time to find a team! Check out the <%= link_to "teams portal", '#' %> to browse available teams or create one of your own for others to join. If you're looking to play right this second you can always add a toon to the <%= link_to "live players", listings_path %> scroll and let others find you for a game now!
		</ol>
	</p>
	<br>


	<p>
	<h2>Why Use RBG Hub?</h2>
		RBG Hub is a lightweight, mobile-friendly service focusing exclusively on Rated Battlegrounds for World of Warcraft. Not everyone has the luxury of a regular RBG group, but now with WoW's cross-server RBG availability finding players of equal skill and schedule has never been easier.</p>
		<p>
		Only want to play with 1500+ players, Sunday mornings between 8a-11a PST? Looking for a specific class to fill that last spot? Create or search for raids with filters and connect with people just like you!

	</p>

</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<% unless signed_in? %>
	<center>
		<div class="hero-unit">
			<h1 class="brand">RBGhub.com</h1><br>
			<h3>Find or create a cross-realm Rated Battleground raid in minutes</h3>
			<%= link_to "Login Now >>", new_user_session_path, class: "btn btn-primary" %>
		</div>
	</center>

	<div class="row">
		<div class="span4">
			<div class="well">
				<center>
					<h2 class="brand">Step 1</h2>
					<p>Create an account to get started</p>
					<%= link_to "Create Account", new_user_registration_path, class: "btn btn-success" %>
				</center>  	
			</div>
		</div>

		<div class="span4">
			<div class="well">
				<center>
					<h2 class="brand">Step 2</h2>
					<p>Add or manage toons on your roster</p>
					<%= link_to "My Roster", characters_path, class: "btn btn-success" %>
				</center>
			</div>
		</div>

		<div class="span4">
			<div class="well">
				<center>
					<h2 class="brand">Step 3</h2>
					<p>Find or create a team that fits your schedule</p>
					<%= link_to "Join A Team", '#', class: "btn btn-success" %>
				</center>
			</div>
		</div>
	</div>

<% else %>
	<center>
		<div class="hero-unit">
			<h1 class="brand">RBGhub.com</h1><br>
			<h3>Find or create a cross-realm Rated Battleground raid in minutes</h3>
			<%= link_to "My Roster", characters_path, class: "btn btn-primary" %>
			<%= link_to "Teams Hub", '#', class: "btn btn-primary" %>
		</div>
	</center>

		<div class="row">
			<div class="span4">
				<div class="well">
				</div>
			</div>

			<div class="span4">
				<div class="well">
				</div>
			</div>

			<div class="span4">
				<div class="well">
				</div>
			</div>
		</div>


<% end %>