config/routes.rb
Rbghub::Application.routes.draw do

  resources :teamstats

  resources :characters

  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'roster' => 'characters#index'
  get 'stats' => 'teamstats#new'
  

  get 'sitemap.xml' => "pages#sitemap.xml"

 root 'teamstats#new'

  

end

app/models/character.rb
class Character < ActiveRecord::Base
	attr_accessible :name, :realm

	validates :name, presence: true
	validates :realm, presence: true
	validates :user_id, presence: true

	belongs_to :user
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json

  def index
    @characters = Character.order(sort_column + ' ' + sort_direction)
    
  end


  # GET /characters/1
  # GET /characters/1.json
  def show    

    armory = HTTParty.get("http://us.battle.net/api/wow/character/" + @character.realm + "/" + @character.name + "?fields=stats,pvp,items,achievements")
    @character.ilvl = armory["items"]["averageItemLevelEquipped"]    
    @character.cr = armory["pvp"]["brackets"]["ARENA_BRACKET_RBG"]["rating"]
    @character.arena2 = armory["pvp"]["brackets"]["ARENA_BRACKET_2v2"]["rating"]
    @character.arena3 = armory["pvp"]["brackets"]["ARENA_BRACKET_3v3"]["rating"]
    @character.arena5 = armory["pvp"]["brackets"]["ARENA_BRACKET_5v5"]["rating"]
    @character.pvppower = armory["stats"]["pvpPowerRating"]
    @character.pvpresil = armory["stats"]["pvpResilienceRating"]
    @character.hk = armory["totalHonorableKills"]
    @character.health = armory["stats"]["health"]
    @character.armor = armory["stats"]["armor"]
    @character.str = armory["stats"]["str"]
    @character.agi = armory["stats"]["agi"]
    @character.int = armory["stats"]["int"]
    @character.spr = armory["stats"]["spr"]
    @character.ap = armory["stats"]["attackPower"]
    @character.sp = armory["stats"]["spellPower"]
    @character.mastery = armory["stats"]["masteryRating"]
    @character.masteryp = armory["stats"]["mastery"]
    @character.crit = armory["stats"]["critRating"]
    @character.critp = armory["stats"]["crit"]
    @character.haste = armory["stats"]["hasteRating"]
    @character.hastep = armory["stats"]["haste"]

    @achievements = armory["achievements"]["achievementsCompleted"]
    
    #2s achieves
    if @achievements.include? 1159
      @character.achv2 = 2200
    elsif @achievements.include? 401
      @character.achv2 = 2000
    elsif @achievements.include? 400
      @character.achv2 = 1750
    elsif @achievements.include? 399
      @character.achv2 = 1550
    end
    
    #3s achieves
    if @achievements.include? 5267
      @character.achv3 = 2700
    elsif @achievements.include? 5266
      @character.achv3 = 2400
    elsif @achievements.include? 1160
      @character.achv3 = 2200
    elsif @achievements.include? 405
      @character.achv3 = 2000
    elsif @achievements.include? 403
      @character.achv3 = 1750
    elsif @achievements.include? 402
      @character.achv3 = 1550
    end
        
    #5s achieves
    if @achievements.include? 1161
      @character.achv5 = 2200
    elsif @achievements.include? 404
      @character.achv5 = 2000
    elsif @achievements.include? 407
      @character.achv5 = 1750
    elsif @achievements.include? 406
      @character.achv5 = 1550
    end

    #PVP Titles
    if @achievements.include? 2091
      @character.bgtitle = "Gladiator"
    elsif @achievements.include? 2092
      @character.bgtitle = "Duelist"
    elsif @achievements.include? 2093
      @character.bgtitle = "Rival"
    elsif @achievements.include? 2090
      @character.bgtitle = "Challenger"
    end

    #ArenaMaster Title
    if @achievements.include? 1174
      @character.arenamaster = true
    end

    @character.save
  end

  # GET /characters/new
  def new
    @character = current_user.characters.new
  end

  # GET /characters/1/edit
  def edit
    @characters = current_user.characters.find(params[:id])
    @character.name.capitalize!
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = current_user.characters.new(character_params)
    @character.name.capitalize!
    armory = HTTParty.get("http://us.battle.net/api/wow/character/" + @character.realm + "/" + @character.name + "?fields=stats,pvp,items")
    @character.arenamaster = false
    @character.gender = armory["gender"]
    @character.cls = armory["class"]
    @character.race = armory["race"]
    @character.ilvl = armory["items"]["averageItemLevelEquipped"]
    @character.cr = armory["pvp"]["brackets"]["ARENA_BRACKET_RBG"]["rating"]    
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render action: 'show', status: :created, location: @character }
      else
        format.html { render action: 'new' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = current_user.characters.find(params[:id])
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :realm)
    end

    private
      def sort_column
        Character.column_names.include?(params[:sort]) ? params[:sort] : "name"
      end
      
      def sort_direction
        %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
      end


end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_back.html.erb
<div class="row">
	<div class="span12">
		<div class="well">
			<center>
				<%= link_to '<< Back to my roster', roster_path, class: "btn btn-primary" %>
			</center>
		</div>
	</div>
</div>

app/views/characters/_character.html.erb
<% if current_user == character.user %>


	<tr>
		<td><%= link_to character.name, character %></td>
		<td>
			<!--Tauren-->
			<% if character.race == 6 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212064706/wowwiki/images/c/cb/Tauren_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 6 && character.gender == 0 %>
				<%= image_tag "http://images4.wikia.nocookie.net/__cb20071212064733/wowwiki/images/b/ba/Tauren_Male_32x32.png", height: '32', width: '32' %>
			<% end %> 

			<!--Undead-->
			<% if character.race == 5 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212063253/wowwiki/images/0/02/Forsaken_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 5 && character.gender == 0 %>
				<%= image_tag "http://images2.wikia.nocookie.net/__cb20071212063341/wowwiki/images/5/5f/Forsaken_Male_32x32.png", height: '32', width: '32' %>
			<% end %> 

			<!--Orc-->
			<% if character.race == 2 && character.gender == 1 %>
			    <%= image_tag "http://images1.wikia.nocookie.net/__cb20071212064612/wowwiki/images/3/35/Orc_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 2 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20071212064635/wowwiki/images/4/4c/Orc_Male_32x32.png", height: '32', width: '32' %>
			<% end %> 

			<!--Gnome-->
			<% if character.race == 7 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212063423/wowwiki/images/4/43/Gnome_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 7 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20071212063553/wowwiki/images/5/56/Gnome_Male_32x32.png", height: '32', width: '32' %>
			<% end %> 

			<!--Goblin-->
			<% if character.race == 9 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20111022221454/wowwiki/images/c/c1/Goblin_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 9 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20111022221550/wowwiki/images/5/58/Goblin_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Human-->
			<% if character.race == 1 && character.gender == 1 %>
			    <%= image_tag "http://images1.wikia.nocookie.net/__cb20071212064339/wowwiki/images/8/80/Human_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 1 && character.gender == 0 %>
				<%= image_tag "http://images3.wikia.nocookie.net/__cb20071212064436/wowwiki/images/5/56/Human_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Troll-->
			<% if character.race == 8 && character.gender == 1 %>
			    <%= image_tag "http://images1.wikia.nocookie.net/__cb20071212064761/wowwiki/images/7/78/Troll_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 8 && character.gender == 0 %>
				<%= image_tag "http://images3.wikia.nocookie.net/__cb20071212064850/wowwiki/images/c/ce/Troll_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Draenei-->
			<% if character.race == 11 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212062732/wowwiki/images/3/3c/Draenei_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 11 && character.gender == 0 %>
				<%= image_tag "http://images4.wikia.nocookie.net/__cb20071212062806/wowwiki/images/2/2e/Draenei_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Worgen-->
			<% if character.race == 22 && character.gender == 1 %>
			    <%= image_tag "http://a.deviantart.net/avatars/h/e/helasz.png?7", height: '32', width: '32' %>
			<% elsif character.race == 22 && character.gender == 0 %>
				<%= image_tag "http://fc07.deviantart.net/fs70/f/2010/326/d/6/worgen_male_icon_by_murlocaggrob_madmab-d33eq9f.jpg", height: '32', width: '32' %>
			<% end %>

			<!--Blood Elf-->
			<% if character.race == 10 && character.gender == 1 %>
			    <%= image_tag "http://images1.wikia.nocookie.net/__cb20071212062610/wowwiki/images/2/26/BloodElf_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 10 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20071212062644/wowwiki/images/3/30/BloodElf_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Night Elf-->
			<% if character.race == 4 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212064510/wowwiki/images/a/ab/NightElf_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 4 && character.gender == 0 %>
				<%= image_tag "http://images3.wikia.nocookie.net/__cb20071212064537/wowwiki/images/a/ad/NightElf_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Dwarf-->
			<% if character.race == 3 && character.gender == 1 %>
			    <%= image_tag "http://images2.wikia.nocookie.net/__cb20071212062905/wowwiki/images/e/e9/Dwarf_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 3 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20071212063003/wowwiki/images/f/f7/Dwarf_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Panda Ally-->
			<% if character.race == 25 && character.gender == 1 %>
			    <%= image_tag "http://images3.wikia.nocookie.net/__cb20120321050448/wowwiki/images/4/48/Pandaren_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 25 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20111022221708/wowwiki/images/a/a3/Pandaren_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

			<!--Panda Horde-->
			<% if character.race == 26 && character.gender == 1 %>
			    <%= image_tag "http://images3.wikia.nocookie.net/__cb20120321050448/wowwiki/images/4/48/Pandaren_Female_32x32.png", height: '32', width: '32' %>
			<% elsif character.race == 26 && character.gender == 0 %>
				<%= image_tag "http://images1.wikia.nocookie.net/__cb20111022221708/wowwiki/images/a/a3/Pandaren_Male_32x32.png", height: '32', width: '32' %>
			<% end %>

		</td>
		<td>
			<% if character.cls == 6 %>
			    <%= image_tag "http://hydra-media.cursecdn.com/wowpedia.org/e/e5/Ui-charactercreate-classes_deathknight.png", height: '32', width: '32' %>
			<% elsif character.cls == 11 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/6/6f/Ui-charactercreate-classes_druid.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 3 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/4/4e/Ui-charactercreate-classes_hunter.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 8 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/5/56/Ui-charactercreate-classes_mage.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 10 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/2/24/Ui-charactercreate-classes_monk.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 2 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/8/80/Ui-charactercreate-classes_paladin.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 5 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/0/0f/Ui-charactercreate-classes_priest.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 4 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/b/b1/Ui-charactercreate-classes_rogue.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 7 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/3/3e/Ui-charactercreate-classes_shaman.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 9 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/c/cf/Ui-charactercreate-classes_warlock.png", height: '32', width: '32' ) %>
			<% elsif character.cls == 1 %>
			    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/3/37/Ui-charactercreate-classes_warrior.png", height: '32', width: '32' ) %>
			<% end %>
		</td>
		<td><%= character.ilvl %></td>
		<td><%= character.cr %></td>
		<td><%= character.pvppower %></td>
		<td><%= link_to 'Edit Character', edit_character_path(character), class: "btn btn-success pull-right" %></td>
		<td><%= link_to 'Delete Character', character, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" %></td>
	</tr>
<% end %>

app/views/characters/_edit.html.erb
<div class="row">
	<div class="span12">
		<div class="well">
			<center>
				<%= link_to 'Edit ' + @character.name, edit_character_path(@character), class: "btn btn-success" %>
			</center>
		</div>
	</div>
</div>

app/views/characters/_race.html.erb
<% if @character.cls == 6 %>
    <%= image_tag "http://hydra-media.cursecdn.com/wowpedia.org/e/e5/Ui-charactercreate-classes_deathknight.png", height: '64', width: '64' %>
<% elsif @character.cls == 11 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/6/6f/Ui-charactercreate-classes_druid.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 3 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/4/4e/Ui-charactercreate-classes_hunter.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 8 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/5/56/Ui-charactercreate-classes_mage.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 10 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/2/24/Ui-charactercreate-classes_monk.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 2 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/8/80/Ui-charactercreate-classes_paladin.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 5 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/0/0f/Ui-charactercreate-classes_priest.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 4 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/b/b1/Ui-charactercreate-classes_rogue.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 7 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/3/3e/Ui-charactercreate-classes_shaman.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 9 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/c/cf/Ui-charactercreate-classes_warlock.png", height: '64', width: '64' ) %>
<% elsif @character.cls == 1 %>
    <%= image_tag("http://hydra-media.cursecdn.com/wowpedia.org/3/37/Ui-charactercreate-classes_warrior.png", height: '64', width: '64' ) %>
<% end %>

app/views/characters/edit.html.erb
<h1 class="brand">Edit character</h1>

<div class="hero-unit">
	<%= render 'form' %>
</div>


<%= render 'back' %>

app/views/characters/index.html.erb
<% provide(:title, 'My Roster') %>
<div class="hero-unit">
  <h1 class="brand"><%= yield(:title)%></h1><hr>

  <table class="table">
    <thead>
      <tr>
        <th><%= sortable "name", "Character" %></th>
        <th>Race</th>
        <th>Class</th>
        <th><%= sortable "ilvl" %></th>
        <th><%= sortable "cr", "Current Rating" %></th>
        <th><%= sortable "pvppower", "PVP Power" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render @characters %>
    </tbody>
  </table>
    

  <hr>
  <center>
    <%= link_to 'Add Character +', new_character_path, class: "btn btn-primary" %>
  </center>
</div>

app/views/characters/new.html.erb
<% provide(:title, 'Add Character') %>

<div class="hero-unit">
	<h2 class="brand"><%= yield(:title)%></h2><hr>

	<%= render 'form' %>
</div>
	<%= render 'back' %>

app/views/characters/show.html.erb
<% provide(:title, @character.name + ' - ' + @character.realm.capitalize) %>

<div class="hero-unit">
  <center>
    <p><h1 class="brand"> <%= render 'race' %><%= link_to yield(:title), "http://us.battle.net/wow/en/character/" + @character.realm + "/" + @character.name + "/advanced", :target => "blank" %></h1></p>
    <!-- Skill voting, TBD
    <p><h2>Skill: </strong><%= User.find(Character.find(@character).user_id).skill %></h2>
    -->
  </center>
</div>



  <div class="row">
    <div class="span4">
      <div class="well">
        <center>          
          <h3 class="">Core Stats</h3>
          <hr>
        </center>

              <p>
                <strong>Health: </strong><%= number_to_human(@character.health, precision: 4, units: { thousand: "k"}) %><br>
                <strong>Armor: </strong><%= number_to_human(@character.armor, precision: 4, units: { thousand: "k"}) %>
              </p>

              <p>
                <strong>Attack Power: </strong><%= number_to_human(@character.ap, precision: 4, units: { thousand: "k"}) %><br>
                <strong>Spell Power: </strong><%= number_to_human(@character.sp, precision: 4, units: { thousand: "k"}) %><br>
                <strong>Crit: </strong><%= @character.crit %> (<%= number_to_human(@character.critp, precision: 4) %>%)<br>
                <strong>Haste: </strong><%= @character.haste %> (<%= number_to_human(@character.hastep, precision: 4) %>%)<br>
                <strong>Mastery: </strong><%= @character.mastery %> (<%= number_to_human(@character.masteryp, precision: 4) %>%)<br>
              </p>

      </div>
    </div>




    <div class="span4">
      <div class="well">
        <center>
          <h3 class="">PVP Stats</h3>
          <hr>
        </center>
          <p><strong>Resilience: </strong><%= @character.pvpresil %></p>
          <p><strong>PVP Power: </strong><%= @character.pvppower %></p>

          <p><strong>Current RBG Rating: </strong><%= @character.cr %></p>
          <p><strong>Current 2s Rating: </strong><%= @character.arena2 %></p>
          <p><strong>Current 3s Rating: </strong><%= @character.arena3 %></p>
          <p><strong>Current 5s Rating: </strong><%= @character.arena5 %></p>
      </div>
    </div>
    <div class="span4">
      <div class="well">
        <center>
          <h3 class="">Lifetime PVP Stats</h3>
          <hr>
        </center>
          <p><strong>Total HKs: </strong><%= @character.hk %></p>
          <p><strong>Best Arena Title: </strong><%= @character.bgtitle %></p>
          <p><strong>Best 2s Achievement: </strong><%= @character.achv2 %></p>
          <p><strong>Best 3s Achievement: </strong><%= @character.achv3 %></p>
          <p><strong>Best 5s Achievement: </strong><%= @character.achv5 %></p>
          <p><%= link_to @character.name + "\'s Arena Achievements", "http://us.battle.net/wow/en/character/" + @character.realm + "/" + @character.name + "/achievement#95:165", :target => "blank" %></p>
          
      </div>
    </div>
  </div>


<% if current_user == @character.user %>
  <%= render 'edit' %>
<% end %>
  <%= render 'back' %>